spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
#    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
#    healthcheck:
#      enabled: true
    #http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/,
    serviceUrl:
      defaultZone: http://cuixb:1@peer1:8761/eureka/
security:
  user:
    name: cuixb2
    password: 2