server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
security:
  user:
    name: cuixb
    password: 1