server:
  port: 8888
spring:
  application:
    name: zuul0
zuul:
  routes:
    users:
      path: /test/**
      service-id: springbootapp
      sensitiveHeaders: "*" ##springcloud项目中经过网关zuul转发请求后发生session失效问题，这是由于zuul默认会丢弃原来的session并生成新的session，添加这个配置解决
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://cuixb:1@localhost:8761/eureka/
#  instance:
#    preferIpAddress: true