server:
  port: 8888
spring:
  application:
    name: zuul0
zuul:
  routes:
    users:
      path: /test/**
      service-id: springbootapp
#      sensitiveHeaders: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://cuixb:1@localhost:8761/eureka/
#  instance:
#    preferIpAddress: true